export const songs = [
    { name: "Echoes of Time", artist: "Lunar Waves", duration: 92 },
    { name: "Summer Breeze", artist: "Ocean Sun", duration: 135 },
    { name: "Midnight Stroll", artist: "Neon Nights", duration: 128 },
    { name: "Velvet Horizon", artist: "Skyline Groove", duration: 138 },
    { name: "Golden Hour", artist: "Aurora Dreams", duration: 94 },
    { name: "Dancing Lights", artist: "Prism Beats", duration: 122 },
    { name: "Celestial Glow", artist: "Starry Sky", duration: 120 },
    { name: "Shimmering Sands", artist: "Desert Bloom", duration: 97 },
    { name: "Twilight Serenade", artist: "Evening Harmony", duration: 140 },
    { name: "Crystal Forest", artist: "Emerald Echo", duration: 105 },
    { name: "Urban Rhythm", artist: "City Vibes", duration: 118 },
    { name: "Wandering Souls", artist: "Mystic Notes", duration: 133 },
    { name: "Ethereal Journey", artist: "Cloud Wanderer", duration: 136 },
    { name: "Chasing Shadows", artist: "Dark Whisper", duration: 91 },
    { name: "Mountain Echo", artist: "Highland Tune", duration: 110 },
    { name: "Liquid Gold", artist: "Golden Strings", duration: 138 },
    { name: "Moonlit Sonata", artist: "Lunar Notes", duration: 112 },
    { name: "Cascade Symphony", artist: "Waterfall Vibes", duration: 137 },
    { name: "Hidden Oasis", artist: "Sahara Sound", duration: 102 },
    { name: "Aurora Pulse", artist: "Arctic Glow", duration: 123 },
    { name: "Serenade by the Sea", artist: "Ocean Chords", duration: 95 },
    { name: "Galaxy Groove", artist: "Cosmic Beat", duration: 130 },
    { name: "Forest Whispers", artist: "Canopy Tunes", duration: 99 },
    { name: "River of Dreams", artist: "Streamflow", duration: 116 },
    { name: "Electric Dusk", artist: "Voltage Vibe", duration: 125 },
    { name: "Stardust Waltz", artist: "Galactic Dance", duration: 93 },
    { name: "Mystic Dawn", artist: "Horizon Glow", duration: 108 },
    { name: "Solar Winds", artist: "Planet Groove", duration: 121 },
    { name: "Crystal Cavern", artist: "Echo Chords", duration: 109 },
    { name: "Velvet Moon", artist: "Nightshade", duration: 114 },
];
